experiment:
  preprocessings: ["identic"]  # "asinh", "identic", "log"
  normalisation: True  # False
  models:
#    active: ['sgdr', 'tr', 'poly']  # 'mlp', 'nb', 'lr', 'sgdr', 'tr', 'poly'
    active: ['mlp']  # 'mlp', 'nb', 'lr', 'sgdr', 'tr', 'poly'
    configs:
      mlp:
        hidden_layer_sizes: (100,)
        activation: 'relu'
        solver: 'adam'
        alpha: 0.0001
        batch_size: 'auto'
        learning_rate: 'constant'
        learning_rate_init: 0.001
        power_t: 0.5
        max_iter: 6000
        shuffle: True
        random_state: null
        tol: 1e-4
        verbose: False
        warm_start: False
        momentum: 0.9
        nesterovs_momentum: True
        early_stopping: False
        validation_fraction: 0.1
        beta_1: 0.9
        beta_2: 0.999
        epsilon: 1e-8
        n_iter_no_change: 10
        max_fun: 15000

      nb:
        alpha: 1.0
        fit_prior: True
        class_prior: null
        min_categories: null

      lr:
        penalty: 'l2'
        dual: False
        tol: 1e-4
        C: 1.0
        fit_intercept: True
        intercept_scaling: 1
        class_weight: null
        random_state: null
        solver: 'lbfgs'
        max_iter: 6000
        multi_class: 'auto'
        verbose: 0
        warm_start: False
        n_jobs: null
        l1_ratio: null

      sgdr:
        loss: 'squared_loss'  # later versions implement 'squared_error'
        penalty: 'l2'
        alpha: 0.0001
        l1_ratio: 0.15
        fit_intercept: True
        max_iter: 6000
        tol: 0.001
        shuffle: True
        verbose: 0
        epsilon: 0.1
        random_state: null
        learning_rate: 'invscaling'
        eta0: 0.01
        power_t: 0.25
        early_stopping: False
        validation_fraction: 0.1
        n_iter_no_change: 5
        warm_start: False
        average: False

      tr:
        power: 0.0
        alpha: 1.0
        fit_intercept: True
        link: 'auto'
        max_iter: 6000
        tol: 0.0001
        warm_start: False
        verbose: 0

      poly:
        degree: 3